//! Garbage Collector - BEAM-style generational copying garbage collector.
//!
//! The BEAM GC uses a generational copying collection strategy:
//! - Young heap: nursery generation collected frequently
//! - Old heap: tenured generation collected less frequently
//!
//! The GC is triggered when a process exhausts its heap or after
//! a certain number of allocations. It is a stop-the-world collector
//! per-process (other processes continue running).
//!
//! Stack maps and root maps are critical for correctness:
//! - The compiler generates metadata describing which stack slots
//!   and registers contain heap pointers at each safepoint.
//! - This allows the GC to trace all live references accurately.

use crate::process::Process;
use crate::term::Term;

mod copy;
mod rootset;
mod sweep;

pub use copy::copy_collection;
pub use rootset::RootSet;
pub use sweep::sweep_old_heap;

/// GC statistics for a collection cycle.
#[derive(Debug, Clone, Default)]
pub struct GCStats {
    pub heap_words_before: usize,
    pub heap_words_after: usize,
    pub stack_words: usize,
    pub roots_scanned: usize,
    pub objects_copied: usize,
    pub time_ns: u64,
}

/// GC configuration.
#[derive(Debug, Clone)]
pub struct GCConfig {
    /// Initial nursery size (in words)
    pub nursery_size: usize,
    /// Tenure threshold - objects surviving this many collections are promoted
    pub max_copy: usize,
    /// Full collection threshold (words allocated before triggering full GC)
    pub fullsweep_after: usize,
}

impl Default for GCConfig {
    fn default() -> Self {
        Self {
            nursery_size: 233,
            max_copy: 7,
            fullsweep_after: 65536,
        }
    }
}

/// Perform a garbage collection for the given process.
///
/// This is called when the process needs more heap space or when
/// reductions are exhausted. The GC:
///
/// 1. Scans the root set (stack, registers, mailbox)
/// 2. Copies live objects to a new heap (semi-space copying)
/// 3. Updates all pointers
/// 4. Frees the old heap
///
/// # Safety
///
/// This function must be called at a safepoint - all live references
/// must be visible on the stack or in the root set. The compiler
/// generates stack maps that describe which slots contain pointers.
pub unsafe fn collect(process: &mut Process, need_words: usize) -> Result<(), &'static str> {
    let _stats = GCStats::default();
    log::trace!(
        "GC triggered for process {}: heap_ptr={:?}, need={} words",
        process.pid,
        process.heap_ptr,
        need_words
    );

    // 1. Build root set first (needs &mut process)
    let rootset = RootSet::from_process(process);

    // 2. Calculate live size from root set + heap
    let live_size = (process.heap_ptr as usize) - (process.heap_start() as usize);
    let new_size = (live_size * 2).max(need_words).max(233);

    // 3. Perform copying collection (needs &mut process)
    let new_heap = copy_collection(process, new_size)?;

    // 4. Update root pointers after collection
    // (copy_collection already updates registers and stack in-place)

    // 4. Update process heap pointer
    process.heap_ptr = new_heap;

    log::trace!("GC complete for process {}", process.pid);

    Ok(())
}

/// Check if GC is needed and perform it if so.
///
/// Called by the AOT-compiled code before allocations.
/// Returns the updated heap pointer after potential GC.
pub unsafe fn maybe_collect(process: &mut Process, need_words: usize) -> *mut Term {
    let available = process.heap_top as usize - process.heap_ptr as usize;
    if available < need_words {
        collect(process, need_words).expect("GC failed");
    }
    let ptr = process.heap_ptr;
    process.heap_ptr = unsafe { process.heap_ptr.add(need_words) };
    ptr
}

/// Safepoint marker - indicates that all live values are on the stack.
///
/// The AOT compiler inserts calls to this function at points where
/// GC may occur. The stack map at each safepoint describes which
/// stack slots and registers contain live heap pointers.
#[inline(always)]
pub fn safepoint() {
    // In a full implementation, this would:
    // 1. Check if GC is requested
    // 2. If so, perform GC with the stack map for this safepoint
    // The stack map is generated by the compiler and stored alongside
    // the compiled code.
}

/// Stack map entry - describes a single stack slot at a safepoint.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct StackMapEntry {
    /// Offset from stack base (in words)
    pub offset: u32,
    /// Whether this slot contains a pointer (vs. immediate value)
    pub is_pointer: bool,
    /// If pointer, the type of value (for precise GC)
    pub value_type: StackMapType,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy)]
pub enum StackMapType {
    Unknown,
    TuplePointer,
    ListPointer,
    BoxedPointer,
    FunPointer,
    MapPointer,
    BinaryPointer,
    MaybePointer, // could be either immediate or pointer
}

/// A stack map for a single safepoint in compiled code.
#[repr(C)]
pub struct StackMap {
    /// The instruction offset this map corresponds to
    pub instruction_offset: u32,
    /// Number of live entries
    pub num_entries: u32,
    /// The live stack slots
    pub entries: [StackMapEntry; 0], // Flexible array member
}

impl StackMap {
    /// Iterate over all entries in this stack map.
    pub fn entries(&self) -> &[StackMapEntry] {
        unsafe { std::slice::from_raw_parts(self.entries.as_ptr(), self.num_entries as usize) }
    }
}
